library:
  source-dirs: src
tests:
  bentimes-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bentimes
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- time
- base >= 4.7 && < 5
name: bentimes
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/bentimes
license: BSD3
executables:
  bentimes-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bentimes
description: Please see the README on GitHub at <https://github.com/githubuser/bentimes#readme>
